# Site settings
title: ひとりWeb開発者日報
#email: takeshi.igarashi@gmail.com
description: フリーランスデザイナー兼Webエンジニアっぽい人の日記
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://indigo-design.org" # the base hostname & protocol for your site
permalink: /:year/:month/:title
timezone: Asia/Tokyo
paginate: 10
paginate_path: "/page/:num/"
twitter_username: takeshi81
github_username: takeshi81

# Build settings
markdown: kramdown
kramdown:
  input: GFM
gems:
  - jemoji
  - jekyll-mentions
  - jekyll-redirect-from
#  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
whitelist:
  - jekyll-redirect-from